# Generated by Django 5.2.6 on 2025-09-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
